apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: containersoga/spaistio
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: URL_PORTAL
            value: "https://my.humanresources.com/api/v1"
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
  - port: 80
    targetPort: 80
    name: http
